### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by BeCryptoBee** [ittipong2010/AlienWorlds-Auto-Mining-Bot-Solving-Captha#1]
I Had an error after running the script. As far as I understand, I have to create a folder with a file in the directory with the bot. But what should be in this file?
What can I do with it?
**Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main()
  File "main.py", line 38, in main
    with open('WAXParser/accounts.txt', 'w') as f:**

**Comment by BeCryptoBee** [comment]
I created a file in the specified directory. Wallets signed up for it.
But the problem is that the log says that the mining was successful, but in fact there was no mining.
