### ISSUE TITLE
Doesn't mine.

### ISSUE THREAD

**Issue by BeCryptoBee** [ittipong2010/AlienWorlds-Auto-Mining-Bot-Solving-Captha#2]
There was a mistake in:
_**Traceback (most recent call last):
File "main.py", line 57, in
main()
File "main.py", line 38, in main
with open('WAXParser/accounts.txt', 'w') as f:**_
I created a folder and a file at the specified path. Account names have been added there. Did I do the right thing?
After that, the script ran without errors. Wrote that mining was successful, but in fact there was no mining.
/////////////////////////////////////////////////
Была ошибка в:
_**Traceback (most recent call last):
File "main.py", line 57, in
main()
File "main.py", line 38, in main
with open('WAXParser/accounts.txt', 'w') as f:**_
Я создал папку и файл по указанному пути. В неё добавились имена используемых кошельков/аккаунтов. Правильно ли я поступил?
После этого скрипт запустился без ошибок. Написали, что майнинг прошел успешно, но на самом деле майнинга не было.
Последнее сообщение - _**INFO:Майнинг успешен. Жду следующего майна.**_ . Но майнинг дальше не повторяется, будто  скрипт закончился, хотя он все еще запущен.

**Comment by liiltong** [comment]
> There was a mistake in:
> _**Traceback (most recent call last): File "main.py", line 57, in main() File "main.py", line 38, in main with open('WAXParser/accounts.txt', 'w') as f:**_
> I created a folder and a file at the specified path. Account names have been added there. Did I do the right thing?
> After that, the script ran without errors. Wrote that mining was successful, but in fact there was no mining.
> /////////////////////////////////////////////////
> Была ошибка в:
> _**Traceback (most recent call last): File "main.py", line 57, in main() File "main.py", line 38, in main with open('WAXParser/accounts.txt', 'w') as f:**_
> Я создал папку и файл по указанному пути. В неё добавились имена используемых кошельков/аккаунтов. Правильно ли я поступил?
> После этого скрипт запустился без ошибок. Написали, что майнинг прошел успешно, но на самом деле майнинга не было.
> Последнее сообщение - _**INFO:Майнинг успешен. Жду следующего майна.**_ . Но майнинг дальше не повторяется, будто скрипт закончился, хотя он все еще запущен.


i modified it, need to use many accounts, try my code
